/**
 * Scene 7: FINAL CTA (25-30s)
 */

import { CameraTrack, CameraPresets, ParallaxLayer, EditorialHeading, MetaLabel, RuleLine, SectionNumber, MaskedReveal, CompositionReveal, RuleCross, ImagePanel } from "../primitives";
import React from "react";
import { film, composition, colors, easings, durations, typography, content, motion } from "../../design-tokens";

interface SceneProps { frameOffset?: number; }

export const CTAScene: React.FC<SceneProps> = ({ frameOffset = 0 }) => {
  const { start, end } = film.sections.cta; const duration = end - start; const cta = content.cta;
  return <CameraTrack path={CameraPresets.zoomIn(start + frameOffset, duration * 0.9, 1.08)}>
    <div style={{ position: "absolute", inset: 0, backgroundColor: colors.canvasWarm }} />
    <div style={{ position: "absolute", inset: 0, background: `radial-gradient(ellipse at center, transparent 40%, ${colors.canvasWarm}CC 100%)`, pointerEvents: "none" }} />
    <SectionNumber number={6} total={6} variant="primary" size="large" x={composition.safeMargin} y={composition.safeMargin} divider dividerLength={80} animateFrom={start + frameOffset} animateDuration={durations.cinematic * 30} />
    <EditorialHeading text={cta.headline} variant="massive" x={composition.viewport.width / 2} y={composition.viewport.height / 2 - 180} align="center" color={colors.ink} maskReveal maskDirection="left" animateFrom={start + frameOffset + 30} animateDuration={durations.cinematic * 30} tracking="editorial" />
    <MetaLabel label={cta.subtext} variant="label" animateFrom={start + frameOffset + 90} animateDuration={durations.slow * 30} style={{ position: "absolute", left: composition.viewport.width / 2, top: composition.viewport.height / 2 + 100, transform: "translateX(-50%)" }} />
    <MaskedReveal direction="top" animateFrom={start + frameOffset + 140} animateDuration={durations.cinematic * 30}><div style={{ position: "absolute", left: composition.safeMargin, right: composition.safeMargin, top: composition.viewport.height / 2 + 180, display: "flex", flexDirection: "column", gap: 12, fontFamily: typography.editorial, fontSize: typography.size.meta, fontWeight: typography.weight.regular, lineHeight: typography.leading.relaxed, color: colors.inkMuted, letterSpacing: "0.01em" }}><div>{cta.contact.address}</div><div style={{ marginTop: 16 }}><MetaLabel label="General enquiries" variant="label" /><MetaLabel label={cta.contact.email} variant="location" case="none" /></div><div><MetaLabel label="New business" variant="label" /><MetaLabel label={cta.contact.business} variant="location" case="none" /></div></div></MaskedReveal>
    <div style={{ position: "absolute", left: composition.safeMargin, bottom: composition.safeMargin + 60, display: "flex", gap: 32 }}>{cta.social.map((social, i) => <CompositionReveal key={social} type="fade" animateFrom={start + frameOffset + 200 + i * 10} animateDuration={durations.normal * 30}><MetaLabel label={social} variant="category" animateFrom={start + frameOffset + 200 + i * 10} animateDuration={durations.normal * 30} /></CompositionReveal>)}</div>
    <CompositionReveal type="clip" direction="left" animateFrom={start + frameOffset + 240} animateDuration={durations.slow * 30}><MaskedReveal direction="left" animateFrom={start + frameOffset + 240} animateDuration={durations.normal * 30}><MetaLabel label="Subscribe to our newsletter" variant="label" animateFrom={start + frameOffset + 240} animateDuration={durations.normal * 30} style={{ position: "absolute", right: composition.safeMargin, top: composition.safeMargin + 100, textAlign: "right" }} /></MaskedReveal></CompositionReveal>
    <ParallaxLayer factor={motion.parallax.background}><EditorialHeading text="LET'S WORK TOGETHER" variant="ghost" x={composition.viewport.width / 2 - 900} y={composition.viewport.height / 2 + 300} color={colors.ink} opacity={0.08} tracking="widest" animateFrom={start + frameOffset} animateDuration={duration} /></ParallaxLayer>
    <MaskedReveal direction="top" animateFrom={start + frameOffset + 280} animateDuration={durations.slow * 30}><div style={{ position: "absolute", left: composition.safeMargin, right: composition.safeMargin, bottom: composition.safeMargin, display: "flex", justifyContent: "space-between", alignItems: "flex-end", fontFamily: typography.editorial, fontSize: typography.size.small, fontWeight: typography.weight.regular, color: colors.taupe, letterSpacing: typography.tracking.widest, textTransform: "uppercase" }}><span>{content.footer.copyright}</span><span>{content.footer.rnd}</span><span>{content.footer.built}</span></div></MaskedReveal>
    <RuleCross size={48} thickness={1} color={colors.taupe} x={composition.safeMargin} y={composition.viewport.height - composition.safeMargin - 48} animateFrom={start + frameOffset + 20} animateDuration={durations.normal * 30} />
    <RuleCross size={48} thickness={1} color={colors.taupe} x={composition.viewport.width - composition.safeMargin - 48} y={composition.viewport.height - composition.safeMargin - 48} rotate={45} animateFrom={start + frameOffset + 30} animateDuration={durations.normal * 30} />
    <RuleLine orientation="horizontal" length={composition.viewport.width - composition.safeMargin * 2} thickness={0.5} color={colors.border} x={composition.safeMargin} y={composition.viewport.height - composition.safeMargin - 120} animateFrom={start + frameOffset + 100} animateDuration={durations.slow * 30} draw drawDirection="center" />
    <RuleLine orientation="vertical" length={400} thickness={0.5} color={colors.border} x={composition.viewport.width / 2 - 500} y={composition.viewport.height / 2 - 200} animateFrom={start + frameOffset + 50} animateDuration={durations.cinematic * 30} draw drawDirection="center" />
    <RuleLine orientation="vertical" length={400} thickness={0.5} color={colors.border} x={composition.viewport.width / 2 + 500} y={composition.viewport.height / 2 - 200} animateFrom={start + frameOffset + 50} animateDuration={durations.cinematic * 30} draw drawDirection="center" />
  </CameraTrack>;
};

export const CTASceneImageLed: React.FC<SceneProps> = ({ frameOffset = 0 }) => {
  const { start, end } = film.sections.cta; const duration = end - start; const cta = content.cta;
  return <CameraTrack path={CameraPresets.cinematicDrift(start + frameOffset, duration, 0, -200, 1.1)}>
    <div style={{ position: "absolute", inset: 0, backgroundColor: colors.canvas }} />
    <ParallaxLayer factor={motion.parallax.background}><ImagePanel src="https://picsum.photos/seed/finale/1920/1080.jpg" alt="Finale" variant="bleed" aspectRatio={16/9} fit="cover" opacity={0.12} overlay={colors.ink} overlayOpacity={0.05} parallaxFactor={motion.parallax.background} animateFrom={start + frameOffset} animateDuration={duration} /></ParallaxLayer>
    <SectionNumber number={6} total={6} variant="primary" size="large" x={composition.safeMargin} y={composition.safeMargin} divider dividerLength={80} animateFrom={start + frameOffset} animateDuration={durations.cinematic * 30} />
    <EditorialHeading text={cta.headline} variant="architectural" x={composition.viewport.width / 2} y={composition.viewport.height / 2 - 100} align="center" color={colors.white} maskReveal maskDirection="left" animateFrom={start + frameOffset + 30} animateDuration={durations.cinematic * 30} tracking="editorial" />
    <MetaLabel label={cta.subtext} variant="label" color={colors.champagne} animateFrom={start + frameOffset + 90} animateDuration={durations.slow * 30} style={{ position: "absolute", left: composition.viewport.width / 2, top: composition.viewport.height / 2 + 120, transform: "translateX(-50%)" }} />
    <ParallaxLayer factor={motion.parallax.foreground}><MaskedReveal direction="top" animateFrom={start + frameOffset + 150} animateDuration={durations.cinematic * 30}><div style={{ position: "absolute", left: composition.safeMargin, bottom: composition.safeMargin + 120, display: "flex", flexDirection: "column", gap: 8, fontFamily: typography.editorial, fontSize: typography.size.meta, fontWeight: typography.weight.regular, lineHeight: typography.leading.relaxed, color: colors.champagne }}><div>{cta.contact.address}</div><div style={{ marginTop: 16 }}><MetaLabel label="General enquiries" variant="label" color={colors.champagne} /><MetaLabel label={cta.contact.email} variant="location" case="none" color={colors.champagne} /></div></div></MaskedReveal></ParallaxLayer>
    <ParallaxLayer factor={motion.parallax.foreground}><div style={{ position: "absolute", right: composition.safeMargin, bottom: composition.safeMargin + 80, display: "flex", flexDirection: "column", gap: 16, alignItems: "flex-end" }}>{cta.social.map((social, i) => <CompositionReveal key={social} type="fade" animateFrom={start + frameOffset + 200 + i * 10} animateDuration={durations.normal * 30}><MetaLabel label={social} variant="category" color={colors.champagne} align="right" animateFrom={start + frameOffset + 200 + i * 10} animateDuration={durations.normal * 30} /></CompositionReveal>)}</div></ParallaxLayer>
    <MaskedReveal direction="top" animateFrom={start + frameOffset + 280} animateDuration={durations.slow * 30}><div style={{ position: "absolute", left: composition.safeMargin, right: composition.safeMargin, bottom: composition.safeMargin, display: "flex", justifyContent: "space-between", alignItems: "flex-end", fontFamily: typography.editorial, fontSize: typography.size.small, fontWeight: typography.weight.regular, color: colors.taupe, letterSpacing: typography.tracking.widest, textTransform: "uppercase" }}><span>{content.footer.copyright}</span><span>{content.footer.rnd}</span><span>{content.footer.built}</span></div></MaskedReveal>
    <SectionNumber number={6} variant="ghost" size="architectural" x={composition.viewport.width - composition.safeMargin - 300} y={composition.safeMargin + 100} rotate={-90} opacity={0.05} animateFrom={start + frameOffset} animateDuration={duration} />
  </CameraTrack>;
};

export default CTAScene;