/**
 * EditorialHeading - Large-scale typographic compositions
 */

import { interpolate, useCurrentFrame } from "remotion";
import React from "react";
import { typography, colors, easings, durations } from "../../design-tokens";

interface EditorialHeadingProps { text: string; variant?: "display" | "hero" | "massive" | "architectural" | "outline" | "ghost"; as?: "h1" | "h2" | "h3" | "div" | "span"; align?: "left" | "center" | "right"; tracking?: keyof typeof typography.tracking | string; leading?: keyof typeof typography.leading | number; color?: string; weight?: keyof typeof typography.weight | number; case?: "uppercase" | "lowercase" | "none"; stagger?: boolean; staggerDelay?: number; maskReveal?: boolean; maskDirection?: "left" | "right" | "top" | "bottom" | "center"; crop?: { start?: number; end?: number }; x?: number; y?: number; rotate?: number; scale?: number; opacity?: number; animateFrom?: number; animateDuration?: number; className?: string; style?: React.CSSProperties; }

const VariantStyles: Record<NonNullable<EditorialHeadingProps["variant"]>, React.CSSProperties> = { display: { fontSize: typography.size.display, fontWeight: typography.weight.thin, lineHeight: typography.leading.tight, letterSpacing: typography.tracking.wide }, hero: { fontSize: typography.size.hero, fontWeight: typography.weight.extralight, lineHeight: typography.leading.tight, letterSpacing: typography.tracking.normal }, massive: { fontSize: typography.size.massive, fontWeight: typography.weight.thin, lineHeight: typography.leading.tight, letterSpacing: typography.tracking.wider }, architectural: { fontSize: typography.size.architectural, fontWeight: typography.weight.thin, lineHeight: typography.leading.tight, letterSpacing: typography.tracking.widest }, outline: { fontSize: typography.size.hero, fontWeight: typography.weight.light, lineHeight: typography.leading.tight, letterSpacing: typography.tracking.wide, color: "transparent", WebkitTextStroke: `1px ${colors.ink}` }, ghost: { fontSize: typography.size.massive, fontWeight: typography.weight.thin, lineHeight: typography.leading.tight, letterSpacing: typography.tracking.widest, opacity: 0.15, color: colors.ink } };

export const EditorialHeading: React.FC<EditorialHeadingProps> = ({ text, variant = "display", as: Tag = "h1", align = "left", tracking, leading, color = colors.ink, weight, case: textCase = "none", stagger = false, staggerDelay = 2, maskReveal = false, maskDirection = "left", crop, x = 0, y = 0, rotate = 0, scale = 1, opacity = 1, animateFrom = 0, animateDuration = durations.cinematic * 30, className = "", style = {} }) => {
  const frame = useCurrentFrame(); const v = variant ?? "display"; const variantStyle = VariantStyles[v]; const processedText = textCase === "uppercase" ? text.toUpperCase() : textCase === "lowercase" ? text.toLowerCase() : text; const lines = processedText.split("\n");
  const maskProgress = maskReveal ? interpolate(frame, [animateFrom, animateFrom + animateDuration], [0, 1], { easing: easings.cinematic, extrapolateLeft: "clamp", extrapolateRight: "clamp" }) : 1;
  const fadeProgress = interpolate(frame, [animateFrom, animateFrom + animateDuration * 0.5], [0, 1], { easing: easings.cinematicOut, extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const slideOffset = interpolate(frame, [animateFrom, animateFrom + animateDuration], [60, 0], { easing: easings.cinematic, extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const combinedOpacity = opacity * fadeProgress; const transform = `translate(${x - (maskDirection === "left" ? slideOffset * (1 - maskProgress) : 0)}px, ${y}px) rotate(${rotate}deg) scale(${scale})`;
  const baseStyles: React.CSSProperties = { ...variantStyle, fontFamily: typography.display, color, fontWeight: weight ?? variantStyle.fontWeight, letterSpacing: tracking ?? variantStyle.letterSpacing, lineHeight: leading ?? variantStyle.lineHeight, textAlign: align, textTransform: "none", whiteSpace: "pre-wrap", overflow: "hidden", position: "absolute", left: 0, top: 0, transform, transformOrigin: "left top", opacity: combinedOpacity, pointerEvents: "none", userSelect: "none", ...style };
  const clipPath = crop ? `inset(${crop.start ?? 0}% ${100 - (crop.end ?? 100)}% ${100 - (crop.start ?? 0)}% ${crop.start ?? 0}%)` : "none";
  const maskClipPath = maskReveal ? maskDirection === "left" ? `inset(0 ${100 - maskProgress * 100}% 0 0)` : maskDirection === "right" ? `inset(0 0 0 ${maskProgress * 100}%)` : maskDirection === "top" ? `inset(${100 - maskProgress * 100}% 0 0 0)` : maskDirection === "bottom" ? `inset(0 0 ${100 - maskProgress * 100}% 0)` : `inset(${50 * (1 - maskProgress)}% ${50 * (1 - maskProgress)}% ${50 * (1 - maskProgress)}% ${50 * (1 - maskProgress)}%)` : "none";
  const finalClipPath = crop && maskReveal ? `inset(${crop.start ?? 0}% ${100 - (crop.end ?? 100) + maskProgress * 100}% ${100 - (crop.start ?? 0)}% ${crop.start ?? 0}%)` : crop ? clipPath : maskClipPath;
  if (stagger && processedText.length > 1) { const chars = processedText.split(""); return <Tag className={className} style={{ ...baseStyles, display: "inline-flex", flexWrap: "wrap", clipPath: finalClipPath }} aria-hidden="true">{chars.map((char, i) => { const charFrame = frame - animateFrom - i * staggerDelay; const charProgress = interpolate(charFrame, [0, animateDuration], [0, 1], { easing: easings.cinematic, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); return <span key={i} style={{ display: "inline-block", opacity: charProgress, transform: `translateY(${60 * (1 - charProgress)}px)`, willChange: "opacity, transform" }}>{char === " " ? "\u00A0" : char}</span>; })}</Tag>; }
  return <Tag className={className} style={{ ...baseStyles, clipPath: finalClipPath }} aria-hidden="true">{lines.map((line, i) => <span key={i} style={{ display: "block" }}>{line}{i < lines.length - 1 && <br />}</span>)}</Tag>;
};

interface NumberDisplayProps { number: string | number; prefix?: string; suffix?: string; size?: "meta" | "heading" | "display" | "hero" | "massive"; variant?: "solid" | "outline" | "ghost"; color?: string; opacity?: number; animateFrom?: number; animateDuration?: number; className?: string; }

const NumberSizeStyles: Record<NonNullable<NumberDisplayProps["size"]>, React.CSSProperties> = { meta: { fontSize: typography.size.meta, fontWeight: typography.weight.regular }, heading: { fontSize: typography.size.heading, fontWeight: typography.weight.light }, display: { fontSize: typography.size.display, fontWeight: typography.weight.thin }, hero: { fontSize: typography.size.hero, fontWeight: typography.weight.extralight }, massive: { fontSize: typography.size.massive, fontWeight: typography.weight.thin } };

export const NumberDisplay: React.FC<NumberDisplayProps> = ({ number, prefix = "", suffix = "", size = "display", variant = "solid", color = colors.ink, opacity = 1, animateFrom = 0, animateDuration = durations.cinematic * 30, className = "" }) => { const frame = useCurrentFrame(); const s = size ?? "display"; const progress = interpolate(frame, [animateFrom, animateFrom + animateDuration], [0, 1], { easing: easings.cinematicOut, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); const scale = interpolate(frame, [animateFrom, animateFrom + animateDuration * 0.5], [1.2, 1], { easing: easings.cinematicOut, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); const styles: React.CSSProperties = { ...NumberSizeStyles[s], fontFamily: typography.display, color: variant === "outline" ? "transparent" : color, WebkitTextStroke: variant === "outline" ? `1px ${color}` : undefined, opacity: variant === "ghost" ? opacity * 0.15 : opacity * progress, letterSpacing: typography.tracking.editorial, lineHeight: typography.leading.tight, display: "inline-flex", alignItems: "center", transform: `scale(${scale})`, transformOrigin: "center center", willChange: "opacity, transform" }; return <span className={className} style={styles} aria-hidden="true">{prefix}{number}{suffix}</span>; };

export default EditorialHeading;