/**
 * ImagePanel - Editorial image compositions
 */

import { interpolate, useCurrentFrame } from "remotion";
import React from "react";
import { colors, easings, durations, composition, motion } from "../../design-tokens";

interface ImagePanelProps { src: string; alt?: string; variant?: "panel" | "bleed" | "collage" | "crop" | "overlap" | "grid"; aspectRatio?: number; fit?: "cover" | "contain" | "fill" | "none" | "scale-down"; crop?: { top?: number; right?: number; bottom?: number; left?: number }; overlay?: string; overlayOpacity?: number; rule?: boolean; ruleColor?: string; ruleWidth?: number; x?: number; y?: number; width?: number | string; height?: number | string; scale?: number; rotate?: number; opacity?: number; parallaxFactor?: number; reveal?: boolean; revealDirection?: "left" | "right" | "top" | "bottom" | "scale" | "clip"; animateFrom?: number; animateDuration?: number; microMotion?: boolean; className?: string; style?: React.CSSProperties; onClick?: () => void; }

export const ImagePanel: React.FC<ImagePanelProps> = ({ src, alt = "", variant = "panel", aspectRatio = 4/3, fit = "cover", crop, overlay, overlayOpacity = 0, rule = false, ruleColor = colors.border, ruleWidth = 1, x = 0, y = 0, width = "100%", height = "100%", scale = 1, rotate = 0, opacity = 1, parallaxFactor = 1, reveal = false, revealDirection = "clip", animateFrom = 0, animateDuration = durations.cinematic * 30, microMotion = false, className = "", style = {}, onClick }) => {
  const frame = useCurrentFrame();
  const revealProgress = reveal ? interpolate(frame, [animateFrom, animateFrom + animateDuration], [0, 1], { easing: easings.cinematic, extrapolateLeft: "clamp", extrapolateRight: "clamp" }) : 1;
  const fadeProgress = interpolate(frame, [animateFrom, animateFrom + animateDuration * 0.4], [0, 1], { easing: easings.cinematicOut, extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const microScale = microMotion ? 1 + 0.005 * Math.sin(frame * 0.05) : 1; const microRotate = microMotion ? 0.1 * Math.sin(frame * 0.03) : 0;
  let clipPath = "none"; if (reveal && revealProgress < 1) { switch (revealDirection) { case "left": clipPath = `inset(0 ${100 - revealProgress * 100}% 0 0)`; break; case "right": clipPath = `inset(0 0 0 ${revealProgress * 100}%)`; break; case "top": clipPath = `inset(${100 - revealProgress * 100}% 0 0 0)`; break; case "bottom": clipPath = `inset(0 0 ${100 - revealProgress * 100}% 0)`; break; case "scale": break; default: clipPath = `inset(${50 * (1 - revealProgress)}% ${50 * (1 - revealProgress)}% ${50 * (1 - revealProgress)}% ${50 * (1 - revealProgress)}%)`; } }
  const cropInset = crop ? `inset(${crop.top ?? 0}% ${crop.right ?? 0}% ${crop.bottom ?? 0}% ${crop.left ?? 0}%)` : "none"; const finalClipPath = crop && reveal ? `inset(${crop.top ?? 0}% ${crop.right ?? 0 + (1 - revealProgress) * 100}% ${crop.bottom ?? 0}% ${crop.left ?? 0}%)` : crop ? cropInset : clipPath;
  const variantStyles: Record<string, React.CSSProperties> = { panel: {}, bleed: { width: "100vw", height: "100vh", left: "50%", top: "50%", transform: "translate(-50%, -50%)" }, collage: { borderRadius: "0" }, crop: { overflow: "hidden" }, overlap: { zIndex: 20 }, grid: {} }; const transform = `translate(${x}px, ${y}px) rotate(${rotate + microRotate}deg) scale(${scale * microScale * (reveal && revealDirection === "scale" ? revealProgress : 1)})`;
  return <div className={className} style={{ position: "absolute", left: typeof width === "string" && width.endsWith("%") ? width : `${x}px`, top: typeof height === "string" && height.endsWith("%") ? height : `${y}px`, width: typeof width === "number" ? `${width}px` : width, height: typeof height === "number" ? `${height}px` : height, transform, transformOrigin: "center center", opacity: opacity * fadeProgress * revealProgress, clipPath: finalClipPath, willChange: "transform, opacity, clip-path", pointerEvents: onClick ? "auto" : "none", cursor: onClick ? "pointer" : "default", ...variantStyles[variant], ...style }} onClick={onClick} data-parallax-factor={parallaxFactor}><div style={{ position: "absolute", inset: 0, backgroundImage: `url(${src})`, backgroundSize: fit, backgroundPosition: "center", backgroundRepeat: "no-repeat", clipPath: crop ? cropInset : "none" }} aria-hidden="true" />{overlay && <div style={{ position: "absolute", inset: 0, backgroundColor: overlay, opacity: overlayOpacity, pointerEvents: "none" }} aria-hidden="true" />}{rule && <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, height: ruleWidth, backgroundColor: ruleColor, pointerEvents: "none" }} aria-hidden="true" />}</div>;
};

interface ImageCollageProps { images: Array<{ src: string; alt?: string; x: number; y: number; width: number; height: number; rotate?: number; scale?: number; zIndex?: number; reveal?: boolean; revealDelay?: number }>; containerWidth?: number; containerHeight?: number; background?: string; animateFrom?: number; staggerDelay?: number; className?: string; }

export const ImageCollage: React.FC<ImageCollageProps> = ({ images, containerWidth = composition.viewport.width, containerHeight = composition.viewport.height, background = "transparent", animateFrom = 0, staggerDelay = 8, className = "" }) => { const frame = useCurrentFrame(); return <div className={className} style={{ position: "relative", width: containerWidth, height: containerHeight, backgroundColor: background, overflow: "hidden" }}>{images.map((img, i) => { const imgAnimateFrom = animateFrom + i * staggerDelay; const revealProgress = img.reveal ? interpolate(frame, [imgAnimateFrom, imgAnimateFrom + durations.cinematic * 30], [0, 1], { easing: easings.cinematic, extrapolateLeft: "clamp", extrapolateRight: "clamp" }) : 1; return <div key={i} style={{ position: "absolute", left: img.x, top: img.y, width: img.width, height: img.height, transform: `rotate(${img.rotate ?? 0}deg) scale(${img.scale ?? 1} * ${revealProgress})`, transformOrigin: "center center", opacity: revealProgress, zIndex: img.zIndex ?? 10, willChange: "transform, opacity", clipPath: img.reveal ? `inset(${50 * (1 - revealProgress)}% ${50 * (1 - revealProgress)}% ${50 * (1 - revealProgress)}% ${50 * (1 - revealProgress)}%)` : "none" }} data-parallax-factor={1.05}><div style={{ position: "absolute", inset: 0, backgroundImage: `url(${img.src})`, backgroundSize: "cover", backgroundPosition: "center", backgroundRepeat: "no-repeat" }} aria-hidden="true" /></div>; })}</div>; };

export default ImagePanel;