/**
 * MaskedReveal - Reveal animations using CSS clip-path masks
 */

import { interpolate, useCurrentFrame } from "remotion";
import React from "react";
import { easings, durations } from "../../design-tokens";

type MaskDirection = "left" | "right" | "top" | "bottom" | "center" | "horizontal" | "vertical";

interface MaskedRevealProps { children: React.ReactNode; direction?: MaskDirection; animateFrom?: number; animateDuration?: number; easing?: (t: number) => number; initialClip?: number; finalClip?: number; exitAt?: number; exitDuration?: number; customClip?: (progress: number) => string; className?: string; style?: React.CSSProperties; }

export const MaskedReveal: React.FC<MaskedRevealProps> = ({ children, direction = "left", animateFrom = 0, animateDuration = durations.cinematic * 30, easing = easings.cinematic, initialClip = 0, finalClip = 1, exitAt, exitDuration, customClip, className = "", style = {} }) => { const frame = useCurrentFrame(); const enterProgress = interpolate(frame, [animateFrom, animateFrom + animateDuration], [initialClip, finalClip], { easing, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); let exitProgress = 1; if (exitAt !== undefined) { exitProgress = interpolate(frame, [exitAt, exitAt + (exitDuration ?? animateDuration)], [1, 0], { easing, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); } const progress = enterProgress * exitProgress; const getClipPath = (p: number): string => { if (customClip) return customClip(p); const inset = (t: number, r: number, b: number, l: number) => `inset(${t}% ${r}% ${b}% ${l}%)`; switch (direction) { case "left": return inset(0, 100 - p * 100, 0, 0); case "right": return inset(0, 0, 0, p * 100); case "top": return inset(100 - p * 100, 0, 0, 0); case "bottom": return inset(0, 0, 100 - p * 100, 0); case "center": case "horizontal": case "vertical": const v = 50 * (1 - p); return inset(v, v, v, v); default: return "none"; } }; return <div className={className} style={{ position: "relative", clipPath: getClipPath(progress), willChange: "clip-path", ...style }} aria-hidden="true">{children}</div>; };

interface TextMaskRevealProps { text: string; splitBy?: "chars" | "words" | "lines"; direction?: MaskDirection; staggerDelay?: number; animateDuration?: number; easing?: (t: number) => number; style?: React.CSSProperties; as?: "h1" | "h2" | "h3" | "p" | "span" | "div"; className?: string; }

export const TextMaskReveal: React.FC<TextMaskRevealProps> = ({ text, splitBy = "words", direction = "left", staggerDelay = 3, animateDuration = durations.normal * 30, easing = easings.cinematic, style = {}, as: Tag = "h1", className = "" }) => { const frame = useCurrentFrame(); let segments: string[]; if (splitBy === "chars") segments = text.split(""); else if (splitBy === "words") segments = text.split(/(\s+)/).filter(s => s.length > 0); else segments = text.split("\n"); const getClipPath = (p: number): string => { const inset = (t: number, r: number, b: number, l: number) => `inset(${t}% ${r}% ${b}% ${l}%)`; switch (direction) { case "left": return inset(0, 100 - p * 100, 0, 0); case "right": return inset(0, 0, 0, p * 100); case "top": return inset(100 - p * 100, 0, 0, 0); case "bottom": return inset(0, 0, 100 - p * 100, 0); case "center": const v = 50 * (1 - p); return inset(v, v, v, v); default: return "none"; } }; return <Tag className={className} style={{ display: splitBy === "chars" ? "inline-flex" : "block", flexWrap: splitBy === "chars" ? "wrap" : "nowrap", lineHeight: 1.1, ...style }} aria-hidden="true">{segments.map((segment, i) => { const segmentStart = i * staggerDelay; const progress = interpolate(frame, [segmentStart, segmentStart + animateDuration], [0, 1], { easing, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); const isSpace = /^\s+$/.test(segment); return <span key={i} style={{ display: "inline-block", clipPath: getClipPath(progress), willChange: "clip-path", whiteSpace: isSpace ? "pre" : "nowrap" }}>{isSpace ? "\u00A0" : segment}</span>; })}</Tag>; };

interface ImageMaskRevealProps { src: string; alt?: string; direction?: MaskDirection; animateFrom?: number; animateDuration?: number; easing?: (t: number) => number; fit?: "cover" | "contain" | "fill"; aspectRatio?: number; parallaxFactor?: number; className?: string; style?: React.CSSProperties; }

export const ImageMaskReveal: React.FC<ImageMaskRevealProps> = ({ src, alt = "", direction = "left", animateFrom = 0, animateDuration = durations.cinematic * 30, easing = easings.cinematic, fit = "cover", aspectRatio = 4/3, parallaxFactor = 1, className = "", style = {} }) => { const frame = useCurrentFrame(); const progress = interpolate(frame, [animateFrom, animateFrom + animateDuration], [0, 1], { easing, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); const getClipPath = (p: number): string => { const inset = (t: number, r: number, b: number, l: number) => `inset(${t}% ${r}% ${b}% ${l}%)`; switch (direction) { case "left": return inset(0, 100 - p * 100, 0, 0); case "right": return inset(0, 0, 0, p * 100); case "top": return inset(100 - p * 100, 0, 0, 0); case "bottom": return inset(0, 0, 100 - p * 100, 0); case "center": const v = 50 * (1 - p); return inset(v, v, v, v); default: return "none"; } }; return <div className={className} style={{ position: "relative", aspectRatio, overflow: "hidden", backgroundColor: "#f0f0f0", ...style }} data-parallax-factor={parallaxFactor}><div style={{ position: "absolute", inset: 0, backgroundImage: `url(${src})`, backgroundSize: fit, backgroundPosition: "center", backgroundRepeat: "no-repeat", clipPath: getClipPath(progress), willChange: "clip-path" }} aria-hidden="true" /></div>; };

interface CompositionRevealProps { children: React.ReactNode; type?: "slide" | "clip" | "scale" | "parallax" | "fade"; direction?: "left" | "right" | "up" | "down"; animateFrom?: number; animateDuration?: number; easing?: (t: number) => number; delay?: number; className?: string; style?: React.CSSProperties; }

export const CompositionReveal: React.FC<CompositionRevealProps> = ({ children, type = "clip", direction = "left", animateFrom = 0, animateDuration = durations.cinematic * 30, easing = easings.cinematic, delay = 0, className = "", style = {} }) => { const frame = useCurrentFrame(); const effectiveStart = animateFrom + delay; const progress = interpolate(frame, [effectiveStart, effectiveStart + animateDuration], [0, 1], { easing, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); let transform = "none"; let clipPath = "none"; let opacity = 1; switch (type) { case "slide": { const d = 100 * (1 - progress); switch (direction) { case "left": transform = `translateX(-${d}%)`; break; case "right": transform = `translateX(${d}%)`; break; case "up": transform = `translateY(-${d}%)`; break; case "down": transform = `translateY(${d}%)`; break; } break; } case "clip": { const inset = (t: number, r: number, b: number, l: number) => `inset(${t}% ${r}% ${b}% ${l}%)`; switch (direction) { case "left": clipPath = inset(0, 100 - progress * 100, 0, 0); break; case "right": clipPath = inset(0, 0, 0, progress * 100); break; case "up": clipPath = inset(100 - progress * 100, 0, 0, 0); break; case "down": clipPath = inset(0, 0, 100 - progress * 100, 0); break; } break; } case "scale": { transform = `scale(${0.95 + 0.05 * progress})`; opacity = progress; break; } case "parallax": { const d = 50 * (1 - progress); switch (direction) { case "left": transform = `translateX(${d}px)`; break; case "right": transform = `translateX(-${d}px)`; break; case "up": transform = `translateY(${d}px)`; break; case "down": transform = `translateY(-${d}px)`; break; } break; } default: opacity = progress; } return <div className={className} style={{ position: "relative", transform, clipPath, opacity, willChange: "transform, clip-path, opacity", ...style }}>{children}</div>; };

export default MaskedReveal;