/**
 * MetaLabel - Small editorial metadata typography
 */

import { interpolate, useCurrentFrame } from "remotion";
import React from "react";
import { typography, colors, easings, durations } from "../../design-tokens";

interface MetaLabelProps { label: string; value?: string | number; variant?: "label" | "stat" | "category" | "location" | "number" | "badge"; case?: "uppercase" | "lowercase" | "none"; color?: string; align?: "left" | "center" | "right"; gap?: number; animateFrom?: number; animateDuration?: number; staggerIndex?: number; staggerDelay?: number; className?: string; style?: React.CSSProperties; }

const VariantStyles: Record<NonNullable<MetaLabelProps["variant"]>, React.CSSProperties> = { label: { fontSize: typography.size.meta, fontWeight: typography.weight.regular, letterSpacing: typography.tracking.editorial, textTransform: "uppercase", color: colors.inkMuted }, stat: { fontSize: typography.size.heading, fontWeight: typography.weight.light, letterSpacing: typography.tracking.wide, lineHeight: typography.leading.tight, color: colors.ink }, category: { fontSize: typography.size.small, fontWeight: typography.weight.medium, letterSpacing: typography.tracking.widest, textTransform: "uppercase", color: colors.taupe }, location: { fontSize: typography.size.meta, fontWeight: typography.weight.regular, letterSpacing: typography.tracking.wide, color: colors.inkMuted }, number: { fontSize: typography.size.display, fontWeight: typography.weight.thin, letterSpacing: typography.tracking.editorial, lineHeight: typography.leading.tight, color: colors.ink }, badge: { fontSize: typography.size.micro, fontWeight: typography.weight.medium, letterSpacing: typography.tracking.widest, textTransform: "uppercase", color: colors.champagne, backgroundColor: colors.brandDark, padding: `${4}px ${8}px`, borderRadius: 0 } };

export const MetaLabel: React.FC<MetaLabelProps> = ({ label, value, variant = "label", case: textCase = "uppercase", color, align = "left", gap = 16, animateFrom = 0, animateDuration = durations.normal * 30, staggerIndex = 0, staggerDelay = 4, className = "", style = {} }) => { const frame = useCurrentFrame(); const v = variant ?? "label"; const variantStyle = VariantStyles[v]; const effectiveAnimateFrom = animateFrom + staggerIndex * staggerDelay; const fadeProgress = interpolate(frame, [effectiveAnimateFrom, effectiveAnimateFrom + animateDuration * 0.5], [0, 1], { easing: easings.cinematicOut, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); const slideProgress = interpolate(frame, [effectiveAnimateFrom, effectiveAnimateFrom + animateDuration], [30, 0], { easing: easings.cinematic, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); const processedLabel = textCase === "uppercase" ? label.toUpperCase() : textCase === "lowercase" ? label.toLowerCase() : label; return <div className={className} style={{ display: "flex", flexDirection: variant === "badge" ? "row" : "column", alignItems: align === "left" ? "flex-start" : align === "right" ? "flex-end" : "center", gap, opacity: fadeProgress, transform: `translateX(${align === "right" ? -slideProgress : slideProgress}px)`, willChange: "opacity, transform", fontFamily: typography.editorial, ...style }} aria-hidden="true"><span style={{ ...variantStyle, color: color ?? variantStyle.color, textAlign: align }}>{processedLabel}</span>{value !== undefined && <span style={{ ...variantStyle, fontSize: variant === "label" ? typography.size.heading : variantStyle.fontSize, fontWeight: typography.weight.light, letterSpacing: typography.tracking.wide, color: color ?? colors.ink, textAlign: align }}>{value}</span>}</div>; };

interface StatBlockProps { stats: Array<{ value: string | number; label?: string; prefix?: string; suffix?: string }>; direction?: "row" | "column" | "grid"; gap?: number; animateFrom?: number; staggerDelay?: number; className?: string; style?: React.CSSProperties; }

export const StatBlock: React.FC<StatBlockProps> = ({ stats, direction = "row", gap = 48, animateFrom = 0, staggerDelay = 8, className = "", style = {} }) => { const frame = useCurrentFrame(); const layoutStyles = { row: { display: "flex", flexDirection: "row" as const, alignItems: "flex-start" as const, gap }, column: { display: "flex", flexDirection: "column" as const, alignItems: "flex-start" as const, gap: gap / 2 }, grid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap } }; return <div className={className} style={{ ...layoutStyles[direction], ...style }}>{stats.map((stat, i) => <div key={i} style={{ opacity: interpolate(frame, [animateFrom + i * staggerDelay, animateFrom + i * staggerDelay + durations.normal * 30], [0, 1], { easing: easings.cinematicOut, extrapolateLeft: "clamp", extrapolateRight: "clamp" }), transform: `translateY(${interpolate(frame, [animateFrom + i * staggerDelay, animateFrom + i * staggerDelay + durations.cinematic * 30], [30, 0], { easing: easings.cinematic, extrapolateLeft: "clamp", extrapolateRight: "clamp" })}px)`, willChange: "opacity, transform", display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 8 }}><MetaLabel label={stat.value.toString()} variant="stat" animateFrom={animateFrom + i * staggerDelay} staggerIndex={0} />{stat.label && <MetaLabel label={stat.label} variant="label" animateFrom={animateFrom + i * staggerDelay} staggerIndex={1} />}</div>)}</div>; };

export default MetaLabel;