/**
 * RuleLine - Thin editorial rules/lines
 */

import { interpolate, useCurrentFrame } from "remotion";
import React from "react";
import { colors, easings, durations, composition } from "../../design-tokens";

interface RuleLineProps { orientation?: "horizontal" | "vertical" | "diagonal"; length?: number; thickness?: number; color?: string; style?: "solid" | "dashed" | "dotted" | "double"; animateFrom?: number; animateDuration?: number; draw?: boolean; drawDirection?: "start" | "end" | "center"; x?: number; y?: number; rotate?: number; opacity?: number; className?: string; }

export const RuleLine: React.FC<RuleLineProps> = ({ orientation = "horizontal", length = 60, thickness = 1, color = colors.border, style: lineStyle = "solid", animateFrom = 0, animateDuration = durations.slow * 30, draw = true, drawDirection = "start", x = 0, y = 0, rotate = 0, opacity = 1, className = "" }) => { const frame = useCurrentFrame(); const drawProgress = draw ? interpolate(frame, [animateFrom, animateFrom + animateDuration], [0, 1], { easing: easings.cinematic, extrapolateLeft: "clamp", extrapolateRight: "clamp" }) : 1; const fadeProgress = interpolate(frame, [animateFrom, animateFrom + animateDuration * 0.3], [0, 1], { easing: easings.cinematicOut, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); const transformOrigin = drawDirection === "start" ? "left center" : drawDirection === "end" ? "right center" : "center center"; const baseStyles: React.CSSProperties = { position: "absolute", left: x, top: y, transform: `rotate(${rotate}deg)`, transformOrigin, opacity: opacity * fadeProgress, pointerEvents: "none" }; if (orientation === "horizontal") return <div className={className} style={{ ...baseStyles, width: length * drawProgress, height: thickness, backgroundColor: color, borderStyle: lineStyle !== "solid" ? lineStyle : undefined }} aria-hidden="true" />; if (orientation === "vertical") return <div className={className} style={{ ...baseStyles, width: thickness, height: length * drawProgress, backgroundColor: color, borderStyle: lineStyle !== "solid" ? lineStyle : undefined }} aria-hidden="true" />; return <svg className={className} style={{ ...baseStyles, width: length, height: thickness * 4, overflow: "visible" }} aria-hidden="true"><line x1={0} y1={thickness * 2} x2={length * drawProgress} y2={thickness * 2} stroke={color} strokeWidth={thickness} strokeDasharray={lineStyle === "dashed" ? "8,4" : lineStyle === "dotted" ? "2,4" : "none"} style={{ transform: `rotate(${rotate}deg)`, transformOrigin: `${drawDirection === "start" ? "0" : "100%"} 50%` }} /></svg>; };

interface RuleCrossProps { size?: number; thickness?: number; color?: string; gap?: number; animateFrom?: number; animateDuration?: number; x?: number; y?: number; rotate?: number; opacity?: number; className?: string; }

export const RuleCross: React.FC<RuleCrossProps> = ({ size = 24, thickness = 1, color = colors.inkMuted, gap = 4, animateFrom = 0, animateDuration = durations.normal * 30, x = 0, y = 0, rotate = 0, opacity = 1, className = "" }) => { const frame = useCurrentFrame(); const progress = interpolate(frame, [animateFrom, animateFrom + animateDuration], [0, 1], { easing: easings.cinematic, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); const halfSize = size / 2; const halfGap = gap / 2; return <div className={className} style={{ position: "absolute", left: x, top: y, width: size, height: size, transform: `rotate(${rotate}deg)`, opacity, pointerEvents: "none" }} aria-hidden="true"><div style={{ position: "absolute", left: 0, top: `calc(50% - ${thickness / 2}px)`, width: halfSize - halfGap, height: thickness, backgroundColor: color, transform: `scaleX(${progress})`, transformOrigin: "right center" }} /><div style={{ position: "absolute", right: 0, top: `calc(50% - ${thickness / 2}px)`, width: halfSize - halfGap, height: thickness, backgroundColor: color, transform: `scaleX(${progress})`, transformOrigin: "left center" }} /><div style={{ position: "absolute", left: `calc(50% - ${thickness / 2}px)`, top: 0, width: thickness, height: halfSize - halfGap, backgroundColor: color, transform: `scaleY(${progress})`, transformOrigin: "center bottom" }} /><div style={{ position: "absolute", left: `calc(50% - ${thickness / 2}px)`, bottom: 0, width: thickness, height: halfSize - halfGap, backgroundColor: color, transform: `scaleY(${progress})`, transformOrigin: "center top" }} /></div>; };

interface RuleGridProps { columns?: number; rows?: number; cellWidth?: number; cellHeight?: number; color?: string; thickness?: number; animateFrom?: number; animateDuration?: number; stagger?: boolean; className?: string; }

export const RuleGrid: React.FC<RuleGridProps> = ({ columns = 4, rows = 3, cellWidth = 300, cellHeight = 200, color = colors.border, thickness = 0.5, animateFrom = 0, animateDuration = durations.cinematic * 30, stagger = true, className = "" }) => { const frame = useCurrentFrame(); return <div className={className} style={{ position: "absolute", inset: 0, pointerEvents: "none" }}>{Array.from({ length: columns + 1 }).map((_, i) => { const delay = stagger ? i * 3 : 0; const progress = interpolate(frame, [animateFrom + delay, animateFrom + delay + animateDuration], [0, 1], { easing: easings.cinematic, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); return <div key={`v-${i}`} style={{ position: "absolute", left: i * cellWidth, top: 0, width: thickness, height: rows * cellHeight * progress, backgroundColor: color, transformOrigin: "top center" }} />; })} {Array.from({ length: rows + 1 }).map((_, i) => { const delay = stagger ? (columns + 1 + i) * 3 : 0; const progress = interpolate(frame, [animateFrom + delay, animateFrom + delay + animateDuration], [0, 1], { easing: easings.cinematic, extrapolateLeft: "clamp", extrapolateRight: "clamp" }); return <div key={`h-${i}`} style={{ position: "absolute", left: 0, top: i * cellHeight, width: columns * cellWidth * progress, height: thickness, backgroundColor: color, transformOrigin: "left center" }} />; })}</div>; };

export default RuleLine;